src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\User;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $comment;

    /**
     * @ORM\Column(type="integer")
     */
    private $rate;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Episode::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $episode;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getRate(): ?int
    {
        return $this->rate;
    }

    public function setRate(int $rate): self
    {
        $this->rate = $rate;

        return $this;
    }

    //public function getUser(): ?User
    public function getAuthor(): ?User
    {
        return $this->user;
    }

    //public function setUser(?User $user): self
    public function setAuthor(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEpisode(): ?Episode
    {
        return $this->episode;
    }

    public function setEpisode(?Episode $episode): self
    {
        $this->episode = $episode;

        return $this;
    }
}

src/Entity/Program.php
<?php

namespace App\Entity;

use App\Repository\ProgramRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProgramRepository::class)
 * @UniqueEntity(
 * fields = {"title"},
 * message = "Cette série existe déjà."
 * )
 */
class Program
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank(message="ne me laisse pas tout vide")
     * @Assert\Length(max="255", maxMessage="Le nom de la série saisie {{ value }} est trop long, il ne devrait pas dépasser {{ limit }} caractères")
     * @Assert\Regex(
     * pattern="/plus belle la vie/",
     * match=false,
     * message="On parle de vraies séries ici"
     * )  
     */
    private $title;

    /**
    * @ORM\Column(type="text")
    * @Assert\NotBlank(message="ne me laisse pas tout vide") 
    */
    private $summary;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)   
     */
    private $poster;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="programs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=Season::class, mappedBy="program")
     */
    private $seasons;

    /**
     * @ORM\ManyToMany(targetEntity=Actor::class, mappedBy="programs")
     */
    private $actors;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="programs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $owner;

    public function __construct()
    {
        $this->seasons = new ArrayCollection();
        $this->actors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(?string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Season[]
     */
    public function getSeasons(): Collection
    {
        return $this->seasons;
    }

    public function addSeason(Season $season): self
    {
        if (!$this->seasons->contains($season)) {
            $this->seasons[] = $season;
            $season->setProgram($this);
        }

        return $this;
    }

    public function removeSeason(Season $season): self
    {
        if ($this->seasons->removeElement($season)) {
            // set the owning side to null (unless already changed)
            if ($season->getProgram() === $this) {
                $season->setProgram(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Actor[]
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(Actor $actor): self
    {
        if (!$this->actors->contains($actor)) {
            $this->actors[] = $actor;
            $actor->addProgram($this);
        }

        return $this;
    }

    public function removeActor(Actor $actor): self
    {
        if ($this->actors->removeElement($actor)) {
            $actor->removeProgram($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

}

src/Form/ProgramType.php
<?php

namespace App\Form;

use App\Entity\Program;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use App\Entity\Actor;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ProgramType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class)
            ->add('summary', TextareaType::class)
            ->add('poster', TextType::class)
            ->add('category', null, ['choice_label' => 'name'])
            ->add('actors', EntityType::class, [
                'class' => Actor::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true,
                'by_reference' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Program::class,
        ]);
    }
}

src/Controller/ProgramController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Request;
use App\Form\ProgramType;
use App\Entity\Program;
use App\Entity\Season;
use App\Entity\Episode;
use App\Service\Slugify;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Entity\User;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use App\Form\SearchProgramFormType;
use App\Repository\ProgramRepository;

/**
 * @Route("/programs", name="program_")
 */
class ProgramController extends AbstractController
{
    /**
     * Show all rows from Program’s entity
     *
     * @Route("/", name="index")
     * @return Response A response instance
     */
    public function index(Request $request, ProgramRepository $programRepository): Response
    { 
      $form = $this->createForm(SearchProgramFormType::class);
      $form->handleRequest($request);
    
      if ($form->isSubmitted() && $form->isValid()) {
        $search = $form->getData()['search'];
        $programs = $programRepository->findLikeName($search);
    } else {
        $programs = $programRepository->findAll();
    }

/*       $programs = $this->getDoctrine()
      ->getRepository(Program::class)
      ->findAll(); */
    
      return $this->render(
        'program/index.html.twig',
        ['programs' => $programs,
        "form" => $form->createView()]);
    }

     /**
     * The controller for the program add form
     * @param Slugify $slugify
     * @Route("/new", name="new")
     */
    public function new(Request $request, Slugify $slugify, MailerInterface $mailer) : Response
    {
        $program = new Program();
        $form = $this->createForm(ProgramType::class, $program);
        $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();

                $slug = $slugify->generate($program->getTitle());
                $program->setSlug($slug);

                $program->setOwner($this->getUser());

                $entityManager->persist($program);
                $entityManager->flush();

                $email = (new Email())
                ->from($this->getParameter('mailer_from'))
                ->to('your_email@example.com')
                ->subject('Une nouvelle série vient d\'être publiée !')
                ->html($this->renderView('program/newProgramEmail.html.twig', ['program' => $program]));

                $mailer->send($email);

                
                return $this->redirectToRoute('program_index');
                }    
                     
        return $this->render('program/new.html.twig', [
            "form" => $form->createView(),
        ]);
    }



     /**
     * Getting a program by slug
     *
     * @Route("/{slug}", name="show")
     * @ParamConverter("program", class="App\Entity\Program", options={"mapping": {"slug": "slug"}})
     * @return Response
     */
    public function show(Program $program):Response
    {      
        $seasons = $program->getSeasons();          

        if (!$program) {
            throw $this->createNotFoundException(
                'No program with id : '.($program).' found in program\'s table.'
            );
        }
        
        return $this->render('program/show.html.twig', [
            'program' => $program, 
            'seasons' => $seasons,
        ]);
    }

    /**
     * Getting a season 
     *
     * @Route("/{slug}/seasons/{seasonId}", name="season_show")
     * @ParamConverter("program", class="App\Entity\Program", options={"mapping": {"slug": "slug"}})
     * @ParamConverter("seasons", class="App\Entity\Season", options={"mapping": {"seasonId": "id"}})
     * @return Response
     */
    public function showSeason(Program $program, Season $seasons) :Response
    {       
        $episodes = $seasons->getEpisodes(); 

        return $this->render('program/season_show.html.twig', [
            'program' => $program,
            'seasons' => $seasons,
            'episodes' => $episodes
        ]);

    }

        /**
     * Getting an episode
     *
     * @Route("/{slug}/seasons/{seasonId}/episodes/{episodeId}", name="episode_show")
     * @ParamConverter("program", class="App\Entity\Program", options={"mapping": {"slug": "slug"}})
     * @ParamConverter("seasons", class="App\Entity\Season", options={"mapping": {"seasonId": "id"}})
     * @ParamConverter("episodes", class="App\Entity\Episode", options={"mapping": {"episodeId": "id"}})
     * @return Response
     */
    public function showEpisode(Program $program, Season $seasons, Episode $episodes, Request $request) :Response
    {   
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        $user=$this->getUser();
        $comment->setEpisode($episodes);
        $comment->setAuthor($user);
 

         if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();
            return $this->redirectToRoute('comment_index');
        }   

        $comments=$this->getDoctrine()
                       ->getRepository(Comment::class)
                       ->findBy(['episode'=>$episodes]);                      

        return $this->render('program/episode_show.html.twig', [
            'program' => $program,
            'seasons' => $seasons,
            'episodes' => $episodes,
            'comments'=> $comments,
            'form'=> $form->createView()
        ]);
    }

    /**
     * @Route("/{slug}/edit", name="edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Program $program): Response
    {
        $user=$this->getUser();
        $isadmin=false;
        $listeDroits=$user->getRoles();      
 
        foreach ($listeDroits as $value) {
            if ($value=='ROLE_ADMIN')
            {
                $isadmin=true;
            }
        }
        if(!$isadmin)
        {
            if (($this->getUser() != $program->getOwner()))
            {
                throw new AccessDeniedException('Only the owner can edit the program!');
            }

        }

        $form = $this->createForm(ProgramType::class, $program);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('program_index');
        }

        return $this->render('program/edit.html.twig', [
            'program' => $program,
            'form' => $form->createView(),
        ]);
    }

}

templates/program/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/program/_searchform.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/program/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Program{% endblock %}

{% block body %}
    <h1>Edit Program</h1>

    {{ include('program/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('program_index') }}">back to list</a>



    
{% endblock %}

templates/program/episode_show.html.twig
{% extends 'base.html.twig' %}
{% block title %}Série #{{ program.id }}{% endblock %}

{% block body %}
  <div class="media">
    <div class="media-body">
        <h1>{{ program.title }} - Season {{ seasons.number }}<h1>
        <h2> Episode {{ episodes.number }} - {{ episodes.title }}</h2>  
        <p>{{ episodes.synopsis }}</p>
        
    </div>
  </div>

{% if is_granted("ROLE_ADMIN") or is_granted("ROLE_CONTRIBUTOR") %}
    {{ include('comment/_form.html.twig') }}
    {% endif %}

    {% for comment in comments %}
                        <div>                      
                            <div>Commentaire  : {{ comment.comment }} </div>
                            <div>Note {{ comment.rate }}/10 </div>
                            <div>Par {{ comment.author.username }} </div>
                        </div>
                    {% if app.user %}
                        <a href="{{ path('comment_edit', {'id': comment.id}) }}">
                        Editer le commentaire
                        </a>
                    {% endif %}

                     {% else %} 
                        <div>
                            Pas de commentaires
                        </div>
                     {% endfor %} 
 
<a href="{{ path('program_index') }}">
    Retour à la liste des programmes
</a>


{% endblock %}
   

templates/program/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}All programs{% endblock %}

{% block body %}
    <h1>Toutes les séries de la table program : </h1>
 {{ include('program/_searchform.html.twig') }}
    {% for program in programs %}

        <div>
            <h2>{{ loop.index }} / {{ program.title }} - Catégorie : {{ program.category.name }}</h2>
            <p>{{ program.summary }}</p>
            {# Lien vers la fiche de la série : #}
            <a href="{{ path("program_show", { slug: program.slug }) }}">Voir la fiche</a>
            {% if is_granted("ROLE_ADMIN") or is_granted("ROLE_CONTRIBUTOR") %}
             <a href="{{ path('program_edit', { 'slug': program.slug} ) }}">Éditer</a>
            {% endif %}

        </div>       

    {% else %}
        Aucune série trouvée.
    {% endfor %}

    <a href="{{ path('app_index') }}">
        Retour à l'accueil
    </a>


{% endblock %}

   

templates/program/new.html.twig
{% extends "base.html.twig" %}

{% block body %}
    {{ form_start(form, {'attr': {'novalidate': 'novalidate'}})  }}
    {{ form_widget(form) }}
    <input type='submit' value='Add program'>
    {{ form_end(form) }}
{% endblock %}
   

templates/program/newProgramEmail.html.twig
{% extends 'layoutEmail.html.twig' %}

{% block title %}New program{% endblock %}  

{% block body %}
    <h1>New program {{ program.title }} created</h1>

    <p>Hello, the new program {{ program.title }} has been created on Wild Series</p>

    <p>Summary : {{program.summary }}
{% endblock %}
   

templates/program/season_show.html.twig
{% extends 'base.html.twig' %}
{% block title %}Série #{{ program.id }}{% endblock %}

{% block body %}
  <div class="media">
    <div class="media-body">
        <h1>{{ program.title }} - Season {{ seasons.number }}<h1>
            <p>{{ seasons.description }}</p>

  {% for episode in episodes %}
      <div>
        <a href="{{ path("program_episode_show", { slug: program.slug, seasonId: seasons.id, episodeId: episode.id }) }}"><h2> {{ episode.number }} - {{ episode.title }}</h2></a>
      </div>
        {% else %}
        <p>No season to display</p>
      {% endfor %}

    </div>
  </div>

<a href="{{ path('program_index') }}">
    Retour à la liste des programmes
</a>

{% endblock %}
   

templates/program/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}Série #{{ program.id }}{% endblock %}

{% block body %}

<div class="media">
  <img class="align-self-start mr-3" src="{{program.poster}}" alt="{{ program.title }} poster">
  <div class="media-body">
    <h1 class="mt-0">{{ program.title }}</h1>
    <p>{{ program.summary }}</p>
    <p>Catégorie : {{ program.category.name }}</p>
      {% for season in seasons %}
      <div>
        <a href="{{ path("program_season_show", { slug: program.slug, seasonId: season.id }) }}"><h3>Season {{ season.number }} - {{ season.year }}</h3></a>
        <p>{{ season.description }}</p>
        </div>
        {% else %}
        <p>No season to display</p>
      {% endfor %}
      <strong>Acteurs :</strong>
        <ul>
            {% for actor in program.actors %}
                <a href="{{ path("actor_show", { actorId: actor.id }) }}"><li>{{ actor.name }} </li></a>
            {% else %}
                <li>Aucun acteur pour cette série</li>
            {% endfor %}
        </ul>
  </div>
</div>

<a href="{{ path('program_index') }}">
    Retour à la liste des programmes
</a>

{% endblock %}
   